<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>上海生活服务平台</title>
    <style>
        /* 在这里可以添加一些CSS样式来美化你的网页 */
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #333;
            color: #fff;
            padding: 1em;
            text-align: center;
        }
        nav {
            background-color: #444;
            text-align: center;
            padding: 0.5em;
        }
        nav a {
            color: #fff;
            text-decoration: none;
            padding: 0 1em;
        }
        nav a:hover {
            text-decoration: underline;
        }
        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
        }
        .main {
            background-color: #fff;
            padding: 1em;
        }
        footer {
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 1em;
        }
    </style>
 <script>
        window.onload = function() {
            // 获取天气信息
            fetch('https://restapi.amap.com/v3/weather/weatherInfo?key=1170cfb78aeb93c0af211407eb7ee819&city=310000&extensions=base&output=JSON')
                .then(response => response.json())
                .then(data => {
                    var weatherInfo = '今日天气：' + data.lives[0].weather + '<br>温度：' + data.lives[0].temperature + '&deg;C<br>风向：' + data.lives[0].winddirection + '，风力：' + data.lives[0].windpower + '级，<br>湿度：' + data.lives[0].humidity + '，<br>数据发布时间：' + data.lives[0].reporttime;
                    document.getElementById('weather').innerHTML = weatherInfo;
                })
                .catch(error => {
                    console.log('Error fetching weather data: ', error);
                });

            // 监听搜索栏的回车事件
            document.getElementById('searchInput').addEventListener('keyup', function(event) {
                if (event.key === 'Enter') {
                    search(); // 当用户按下回车键时执行搜索功能
                }
            });

            function search() {
                var query = document.getElementById('searchInput').value;
                if (query) {
                    // 根据用户输入的内容跳转到对应的子网页
                    window.location.href = query + '.html'; // 假设子网页的文件名与用户输入的内容相同，并且后缀为.html
                }
            }
        };
</script>
</head>
<body>
    <header>
        <h1>上海生活服务平台</h1>
    </header>
    <nav>
        <a href="餐饮.html">餐饮</a>
        <a href="娱乐.html">娱乐</a>
        <a href="购物.html">购物</a>
        <a href="交通.html">交通</a>
        <a href="旅游.html">旅游</a>
    </nav>
    <div class="container">
        <div class="main">
          <h1>欢迎来到上海生活服务平台</h1>
          <img src="../../27017/Saved Pictures/2275.jpg_wh300.jpg" width="842" height="300" alt=""/>
          
<h1 id="weather">今日天气：</h1>
          <p>这是个为您提供上海生活信息的平台&nbsp;</p>
<em><strong></strong></em>
<input type="text" id="searchInput" placeholder="输入关键词">
            <button onclick="search()">搜索</button>
      </div>
</div>
    <footer>
        <p>&copy; 2023 上海生活服务平台</p>
    </footer>
</body>
</html>
